# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'measure_dharea_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plugin_zajDialogBase(object):
    def setupUi(self, Plugin_zajDialogBase):
        Plugin_zajDialogBase.setObjectName("Plugin_zajDialogBase")
        Plugin_zajDialogBase.resize(987, 738)
        self.button_box = QtWidgets.QDialogButtonBox(Plugin_zajDialogBase)
        self.button_box.setGeometry(QtCore.QRect(630, 690, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label_choose = QtWidgets.QLabel(Plugin_zajDialogBase)
        self.label_choose.setGeometry(QtCore.QRect(100, 30, 271, 81))
        self.label_choose.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_choose.setFont(font)
        self.label_choose.setObjectName("label_choose")
        self.mMapLayerComboBox = QgsMapLayerComboBox(Plugin_zajDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(370, 50, 481, 41))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.pushButton_dh = QtWidgets.QPushButton(Plugin_zajDialogBase)
        self.pushButton_dh.setGeometry(QtCore.QRect(70, 120, 361, 111))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_dh.setFont(font)
        self.pushButton_dh.setObjectName("pushButton_dh")
        self.label_dh = QtWidgets.QLabel(Plugin_zajDialogBase)
        self.label_dh.setGeometry(QtCore.QRect(70, 290, 361, 81))
        self.label_dh.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_dh.setFont(font)
        self.label_dh.setObjectName("label_dh")
        self.label_dh_result = QtWidgets.QLabel(Plugin_zajDialogBase)
        self.label_dh_result.setGeometry(QtCore.QRect(380, 280, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_dh_result.setFont(font)
        self.label_dh_result.setText("")
        self.label_dh_result.setObjectName("label_dh_result")
        self.label_area = QtWidgets.QLabel(Plugin_zajDialogBase)
        self.label_area.setGeometry(QtCore.QRect(70, 380, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_area.setFont(font)
        self.label_area.setObjectName("label_area")
        self.label_area_result = QtWidgets.QLabel(Plugin_zajDialogBase)
        self.label_area_result.setGeometry(QtCore.QRect(410, 380, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_area_result.setFont(font)
        self.label_area_result.setText("")
        self.label_area_result.setObjectName("label_area_result")
        self.pushButton_area = QtWidgets.QPushButton(Plugin_zajDialogBase)
        self.pushButton_area.setGeometry(QtCore.QRect(490, 120, 361, 111))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_area.setFont(font)
        self.pushButton_area.setObjectName("pushButton_area")

        self.retranslateUi(Plugin_zajDialogBase)
        self.button_box.accepted.connect(Plugin_zajDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Plugin_zajDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Plugin_zajDialogBase)

    def retranslateUi(self, Plugin_zajDialogBase):
        _translate = QtCore.QCoreApplication.translate
        Plugin_zajDialogBase.setWindowTitle(_translate("Plugin_zajDialogBase", "Measure_dh_area"))
        self.label_choose.setText(_translate("Plugin_zajDialogBase", "Wybierz warstwę"))
        self.pushButton_dh.setText(_translate("Plugin_zajDialogBase", "Oblicz przewyższenie"))
        self.label_dh.setText(_translate("Plugin_zajDialogBase", "Przewyższenie wynosi: "))
        self.label_area.setText(_translate("Plugin_zajDialogBase", "Pole powierzchni wynosi:"))
        self.pushButton_area.setText(_translate("Plugin_zajDialogBase", "Oblicz pole powierzchni"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Plugin_zajDialogBase = QtWidgets.QDialog()
    ui = Ui_Plugin_zajDialogBase()
    ui.setupUi(Plugin_zajDialogBase)
    Plugin_zajDialogBase.show()
    sys.exit(app.exec_())
